import { createContext, useContext, useState } from 'react';

const translations = {
    en: {
        navHome: "Home",
        navAbout: "About",
        navServices: "Services",
        navContact: "Contact",
        //
        homeTitle: "Welcome to Namin Tax Accounting",
        homeDesc: "Professional tax services for individuals and businesses. Let us help you maximize your refund and minimize your stress!",
        quickTaxEstimate: "Quick Tax Estimate",
        enterIncome: "Enter your annual income (€):",
        estimateTax: "Estimate Tax",
        estimatedTax: "Estimated Tax",
        ourServices: "Our Services",
        contactUs: "Contact Us",
        selectLanguage: "Select Language",
        //
        // Example for English (add to fr and fa as well)
        aboutTitle: "About Namin Tax Accounting",
        aboutDesc: "Namin Tax Accounting is dedicated to providing expert tax and accounting services for individuals, families, and businesses. With years of experience and a commitment to personalized service, we help our clients navigate complex tax regulations and maximize their financial well-being.",
        aboutWhoWeAreTitle: "Who we are",
        aboutWhoWeAre: "We are a small accounting and tax consultancy firm in Belgium. \n Our goal is to provide the best accounting and tax services in Belgium. \n Based on our experience, we have decided to remain a small accounting and tax consultancy firm with a limited number of clients, in order to provide the higest quality service to our clients and respond to their requests within the hour. \n We provide comprehensive services to our clients from different catogeries companies, from setting up a company in Belgium to accounting, administration, tax and VAT returns, etc. \n Currently, we are the only accounting firm to provide our clients with educational videos to better understand their obligations, laws and rights in Belgium in order to make the best decision",
        aboutMissionTitle: "Our Mission",
        aboutMission: "To deliver accurate, timely, and ethical tax solutions while building lasting relationships based on trust and integrity.",
        aboutCredentialsTitle: "Credentials & Experience",
        aboutCredential1: "Certified Accountant (ITAA: 53.460.538)",
        aboutCredential2: "Registered VAT Number: BE1026.447.466",
        aboutCredential3: "Over 15 years of experience in tax consulting and accounting",
        aboutCredential4: "Specialized in Belgian and international tax law",
        aboutWhyTitle: "Why Choose Us?",
        aboutWhy1: "Personalized, one-on-one service",
        aboutWhy2: "Transparent pricing and clear communication",
        aboutWhy3: "Up-to-date knowledge of tax legislation",
        aboutWhy4: "Confidentiality and professionalism guaranteed",
        //
        servicesTitle: "Our Services",
        servicesDesc: "We offer a full range of tax and accounting services for individuals and businesses.",
        taxPrep: "Tax Preparation & Filing",
        consulting: "Tax Consulting",
        bookkeeping: "Bookkeeping",
        payroll: "Payroll Services",
        more: "And more...",
        selectLanguage: "Select Language",
        //
        contactTitle: "Contact Namin Tax Accounting",
        accountantDetails: "Accountant Details",
        nameLabel: "Name",
        emailLabel: "Email",
        phoneLabel: "Phone",
        officeLabel: "Office",
        vatLabel: "VAT No.",
        itaaLabel: "ITAA No.",
        contactUsBtn: "Contact Us",
        sendMessageTitle: "Send a Message",
        yourName: "Your Name",
        yourPhone: "Your Phone Number",
        yourMessage: "Short Message",
        send: "Send",
        cancel: "Cancel",
        allFieldsRequired: "All fields are required.",
        messageSent: "Message sent! Thank you.",
    },
    fr: {
        navHome: "Accueil",
        navAbout: "À propos",
        navServices: "Services",
        navContact: "Contact",
        //
        homeTitle: "Bienvenue chez Namin Tax Accounting",
        homeDesc: "Services fiscaux professionnels pour particuliers et entreprises. Laissez-nous vous aider à maximiser votre remboursement et à minimiser votre stress !",
        quickTaxEstimate: "Estimation rapide des impôts",
        enterIncome: "Entrez votre revenu annuel (€) :",
        estimateTax: "Estimer l'impôt",
        estimatedTax: "Impôt estimé",
        ourServices: "Nos Services",
        contactUs: "Contactez-nous",
        selectLanguage: "Choisir la langue",
        //
        servicesTitle: "Nos Services",
        servicesDesc: "Nous offrons une gamme complète de services fiscaux et comptables pour les particuliers et les entreprises.",
        taxPrep: "Préparation et Déclaration des Impôts",
        consulting: "Conseil Fiscal",
        bookkeeping: "Comptabilité",
        payroll: "Services de Paie",
        more: "Et plus...",
        selectLanguage: "Choisir la langue",
        //
         contactTitle: "Contactez Namin Tax Accounting",
        accountantDetails: "Détails du comptable",
        nameLabel: "Nom",
        emailLabel: "E-mail",
        phoneLabel: "Téléphone",
        officeLabel: "Bureau",
        vatLabel: "N° TVA",
        itaaLabel: "N° ITAA",
        contactUsBtn: "Contactez-nous",
        sendMessageTitle: "Envoyer un message",
        yourName: "Votre nom",
        yourPhone: "Votre numéro de téléphone",
        yourMessage: "Message court",
        send: "Envoyer",
        cancel: "Annuler",
        allFieldsRequired: "Tous les champs sont obligatoires.",
        messageSent: "Message envoyé ! Merci.",
        //
        aboutTitle: "À propos de Namin Tax Accounting",
        aboutDesc: "Namin Tax Accounting s'engage à fournir des services fiscaux et comptables experts aux particuliers, familles et entreprises. Avec des années d'expérience et un engagement envers un service personnalisé, nous aidons nos clients à naviguer dans la complexité des réglementations fiscales et à optimiser leur situation financière.",
        aboutWhoWeAreTitle: "Qui sommes-nous",
        aboutWhoWeAre: "Nous sommes un petit cabinet de conseil en comptabilité et fiscalité en Belgique.\nNotre objectif est de fournir les meilleurs services comptables et fiscaux en Belgique.\nForts de notre expérience, nous avons choisi de rester une petite structure avec un nombre limité de clients afin d’offrir un service de la plus haute qualité et de répondre à leurs demandes dans l’heure.\nNous proposons des services complets à nos clients de différentes catégories d’entreprises, de la création d’entreprise en Belgique à la comptabilité, l’administration, les déclarations fiscales et TVA, etc.\nActuellement, nous sommes le seul cabinet comptable à fournir à nos clients des vidéos éducatives pour mieux comprendre leurs obligations, lois et droits en Belgique afin de prendre les meilleures décisions.",
        aboutMissionTitle: "Notre mission",
        aboutMission: "Fournir des solutions fiscales précises, rapides et éthiques tout en construisant des relations durables basées sur la confiance et l'intégrité.",
        aboutCredentialsTitle: "Qualifications & Expérience",
        aboutCredential1: "Comptable certifié (ITAA : 53.460.538)",
        aboutCredential2: "Numéro de TVA : BE1026.447.466",
        aboutCredential3: "Plus de 15 ans d'expérience en conseil fiscal et comptabilité",
        aboutCredential4: "Spécialisé en droit fiscal belge et international",
        aboutWhyTitle: "Pourquoi nous choisir ?",
        aboutWhy1: "Service personnalisé et individuel",
        aboutWhy2: "Tarification transparente et communication claire",
        aboutWhy3: "Connaissance à jour de la législation fiscale",
        aboutWhy4: "Confidentialité et professionnalisme garantis",
    },
    fa: {
        navHome: "خانه",
        navAbout: "درباره",
        navServices: "خدمات",
        navContact: "تماس",
        //
        homeTitle: "به حسابداری مالیاتی نامین خوش آمدید",
        homeDesc: "خدمات حرفه‌ای مالیاتی برای اشخاص و شرکت‌ها. به شما کمک می‌کنیم بیشترین بازگشت مالیاتی و کمترین استرس را داشته باشید!",
        quickTaxEstimate: "محاسبه سریع مالیات",
        enterIncome: "درآمد سالانه خود را وارد کنید (€):",
        estimateTax: "محاسبه مالیات",
        estimatedTax: "مالیات تخمینی",
        ourServices: "خدمات ما",
        contactUs: "تماس با ما",
        selectLanguage: "انتخاب زبان",
        //
        servicesTitle: "خدمات ما",
        servicesDesc: "ما مجموعه کاملی از خدمات مالیاتی و حسابداری را برای اشخاص و شرکت‌ها ارائه می‌دهیم.",
        taxPrep: "تهیه و ارسال اظهارنامه مالیاتی",
        consulting: "مشاوره مالیاتی",
        bookkeeping: "حسابداری",
        payroll: "خدمات حقوق و دستمزد",
        more: "و بیشتر...",
        selectLanguage: "انتخاب زبان",
        //
         contactTitle: "تماس با حسابداری مالیاتی نامین",
        accountantDetails: "جزئیات حسابدار",
        nameLabel: "نام",
        emailLabel: "ایمیل",
        phoneLabel: "تلفن",
        officeLabel: "دفتر",
        vatLabel: "شماره مالیات بر ارزش افزوده",
        itaaLabel: "شماره ITAA",
        contactUsBtn: "تماس با ما",
        sendMessageTitle: "ارسال پیام",
        yourName: "نام شما",
        yourPhone: "شماره تلفن شما",
        yourMessage: "پیام کوتاه",
        send: "ارسال",
        cancel: "انصراف",
        allFieldsRequired: "همه فیلدها الزامی هستند.",
        messageSent: "پیام ارسال شد! متشکرم.",
        //
        aboutTitle: "درباره حسابداری مالیاتی نامین",
        aboutDesc: "حسابداری مالیاتی نامین متعهد به ارائه خدمات تخصصی مالیاتی و حسابداری به اشخاص، خانواده‌ها و شرکت‌ها است. با سال‌ها تجربه و تعهد به خدمات شخصی‌سازی‌شده، به مشتریان خود کمک می‌کنیم تا در قوانین پیچیده مالیاتی به‌درستی عمل کنند و رفاه مالی خود را به حداکثر برسانند.",
        aboutWhoWeAreTitle: "ما که هستیم",
        aboutWhoWeAre: "ما یک شرکت کوچک مشاوره حسابداری و مالیاتی در بلژیک هستیم.\nهدف ما ارائه بهترین خدمات حسابداری و مالیاتی در بلژیک است.\nبر اساس تجربیاتمان تصمیم گرفته‌ایم یک شرکت کوچک با تعداد محدودی مشتری باقی بمانیم تا بتوانیم بالاترین کیفیت خدمات را ارائه داده و به درخواست‌های مشتریان در کمتر از یک ساعت پاسخ دهیم.\nما خدمات جامعی را به مشتریان خود از دسته‌بندی‌های مختلف شرکت‌ها ارائه می‌دهیم، از ثبت شرکت در بلژیک گرفته تا حسابداری، امور اداری، اظهارنامه‌های مالیاتی و مالیات بر ارزش افزوده و غیره.\nدر حال حاضر، ما تنها شرکت حسابداری هستیم که به مشتریان خود ویدیوهای آموزشی ارائه می‌دهیم تا بهتر بتوانند با وظایف، قوانین و حقوق خود در بلژیک آشنا شوند و بهترین تصمیم را بگیرند.",
        aboutMissionTitle: "ماموریت ما",
        aboutMission: "ارائه راهکارهای مالیاتی دقیق، به‌موقع و اخلاقی و ایجاد روابط پایدار مبتنی بر اعتماد و صداقت.",
        aboutCredentialsTitle: "مدارک و تجربه",
        aboutCredential1: "حسابدار رسمی (ITAA: 53.460.538)",
        aboutCredential2: "شماره مالیات بر ارزش افزوده: BE1026.447.466",
        aboutCredential3: "بیش از ۱۵ سال تجربه در مشاوره مالیاتی و حسابداری",
        aboutCredential4: "متخصص در قوانین مالیاتی بلژیک و بین‌الملل",
        aboutWhyTitle: "چرا ما را انتخاب کنید؟",
        aboutWhy1: "خدمات شخصی و اختصاصی",
        aboutWhy2: "قیمت‌گذاری شفاف و ارتباط روشن",
        aboutWhy3: "دانش به‌روز از قوانین مالیاتی",
        aboutWhy4: "تضمین محرمانگی و حرفه‌ای بودن",
    }
};

const LanguageContext = createContext();

export function LanguageProvider({ children }) {
    const [lang, setLang] = useState('en');
    const t = translations[lang];
    return (
        <LanguageContext.Provider value={{ lang, setLang, t }}>
            {children}
        </LanguageContext.Provider>
    );
}

export function useLanguage() {
    return useContext(LanguageContext);
}

